name: Selenium Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine

    steps:
    - uses: actions/checkout@v2 # Checkout the code
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # Setup JAVA
      with:
        java-version: 17
        distribution: 'adopt'
        steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/wd/hub &
       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
#     - name: Install Google Chrome # Using shell script to install Google Chrome
#       run: |
#        chmod +x ./InstallChrome.sh
#         ./InstallChrome.sh
    - name: Build with Maven
      run: mvn clean test


steps:
- uses: actions/checkout@v2
- uses: nanasess/setup-chromedriver@v1
- run: |
    export DISPLAY=:99
    chromedriver --url-base=/wd/hub &
    sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
